FileVersion = 1
LastConfig = "Debug"
LastPlatform = "Win64"
RecentFilesList = ["src\\Program.bf", "src\\ArrayInteger.bf", "src\\Fichier.bf", "src\\ListInteger.bf", "src\\ArrayIntegerRaw.bf"]

[MainWindow]
X = 0
Y = 0
Width = 1169
Height = 877
ShowKind = "Maximized"

[MainDockingFrame]
Type = "DockingFrame"
SplitType = 2

[[MainDockingFrame.DockedWidgets]]
RequestedWidth = 350.0
RequestedHeight = 200.0
SizePriority = 200.0
Type = "DockingFrame"
SplitType = 1

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
RequestedWidth = 415.0
RequestedHeight = 200.0
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Workspace"
TabWidth = 110.8334
Type = "ProjectPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
IsFillWidget = true
Permanent = true
RequestedWidth = 1500.6
RequestedHeight = 150.0
SizePriority = 1500.6
DefaultDocumentsTabbedView = true
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "ArrayInteger.bf"
TabWidth = 120.8334
Type = "SourceViewPanel"
FilePath = "src\\ArrayInteger.bf"
CursorPos = 184
VertPos = 90.0
ProjectName = "BeefTriRapide"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "ArrayIntegerRaw.bf"
TabWidth = 135.8334
Type = "SourceViewPanel"
FilePath = "src\\ArrayIntegerRaw.bf"
CursorPos = 79
VertPos = 270.0
ProjectName = "BeefTriRapide"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "ListInteger.bf"
TabWidth = 100.8333
Type = "SourceViewPanel"
FilePath = "src\\ListInteger.bf"
CursorPos = 85
VertPos = 270.0
ProjectName = "BeefTriRapide"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Program.bf"
TabWidth = 91.66667
Type = "SourceViewPanel"
FilePath = "src\\Program.bf"
CursorPos = 1438
VertPos = 630.0
ProjectName = "BeefTriRapide"

[[MainDockingFrame.DockedWidgets]]
RequestedWidth = 250.0
RequestedHeight = 382.0
Type = "DockingFrame"
SplitType = 1

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
RequestedWidth = 250.0
RequestedHeight = 250.0
SizePriority = 0.2711158
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Memory"
TabWidth = 95.83334
Type = "MemoryPanel"
AutoResize = "Auto_Mul8"
RequestedWidth = 300.0

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Watch"
TabWidth = 85.00001
Type = "WatchPanel"
Columns = [{Width = 209.0}, {Width = 209.0}, {Width = 209.0}]

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Auto"
TabWidth = 76.66667
Type = "AutoWatchPanel"
Columns = [{Width = 209.0}, {Width = 209.0}, {Width = 209.0}]

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
RequestedWidth = 250.0
RequestedHeight = 250.0
SizePriority = 0.7288842
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Threads"
TabWidth = 93.33334
Type = "ThreadPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Call Stack"
TabWidth = 103.3333
Type = "CallStackPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Immediate"
TabWidth = 110.0
Type = "ImmediatePanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Output"
TabWidth = 88.33334
Type = "OutputPanel"

[[BookmarkFolders]]
Title = ""
